"584":
  title: 2 Fast 2 Furious
  assets:
    - source: youtube
      url: https://www.youtube.com/watch?v=YvHbvnIttec
      filename: theme.mp3
"398978":
  title: The Irishman
  assets:
    - source: youtube
      url: https://www.youtube.com/watch?v=VGI04ICfquQ
      filename: theme.mp3
    - source: http
      url: https://theposterdb.com/api/assets/95010
      filename: poster.jpg
"224372":
  title: A Knight of the Seven Kingdoms
  assets:
    - source: youtube
      url: https://www.youtube.com/watch?v=_2V1F6N8Mx0
      filename: theme.mp3
    - source: http
      url: https://theposterdb.com/api/assets/693676
      filename: poster.jpg
"299534":
  title: Avengers Endgame
  assets:
    - source: youtube
      url: https://www.youtube.com/watch?v=4B3gCHbDu94
      filenmae: theme.mp3

"929590":
  title: Civil War
  assets:
    - source: youtube
      url: https://www.youtube.com/watch?v=fFYMsGj3ZhI
      filename: theme.mp3